CREATE TABLE BANK_STATEMENT
(
    ID                   UUID    NOT NULL UNIQUE,
    DATE_RECORD          DATE    NOT NULL,
    AMOUNT_BALANCE_CENTS INTEGER NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE FINANCIAL_TRANSACTION
(
    ID                 UUID    NOT NULL UNIQUE,
    BANK_STATEMENT_ID  UUID    NOT NULL,
    DATE_RECORD        DATE    NOT NULL,
    AMOUNT_VALUE_CENTS INTEGER NOT NULL,
    IS_PERIODIC        BOOLEAN,
    REASON             TEXT    NOT NULL,
    CHECKSUM           TEXT    NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (BANK_STATEMENT_ID) REFERENCES BANK_STATEMENT (ID)
);
