CREATE TABLE BACKUP_HISTORY
(
    ID             UUID                     NOT NULL UNIQUE,
    LAST_CHECK     TIMESTAMP WITH TIME ZONE NOT NULL,
    HAD_WORK_TO_DO BOOLEAN                  NOT NULL,
    SUCCESS        BOOLEAN                  NOT NULL,
    ERROR_DETAILS  TEXT,

    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_BACKUP_LAST_CHECK ON BACKUP_HISTORY (LAST_CHECK);

ALTER TABLE BACKUP_HISTORY
    ADD CONSTRAINT CO_ERROR_DETAILS_IF_ERROR CHECK (
            (SUCCESS AND ERROR_DETAILS IS NULL) OR (NOT SUCCESS AND ERROR_DETAILS IS NOT NULL)
        );
