ALTER TABLE FINANCIAL_TRANSACTION
    ADD COLUMN CATEGORY TEXT;

UPDATE FINANCIAL_TRANSACTION AS T
SET CATEGORY = C.NAME
FROM CATEGORY AS C
WHERE T.CATEGORY_ID = C.ID;

UPDATE FINANCIAL_TRANSACTION
SET CATEGORY = CATEGORY_ID
WHERE CATEGORY IS NULL;

ALTER TABLE FINANCIAL_TRANSACTION
    ALTER COLUMN CATEGORY SET NOT NULL;
