CREATE TABLE CATEGORY_BUDGET
(
    OWNER_ID                          UUID          NOT NULL,
    CATEGORY_ID                       UUID          NOT NULL UNIQUE,
    ID                                UUID          NOT NULL UNIQUE,

    MONTHLY_BUDGET_AMOUNT_VALUE_CENTS INTEGER       NOT NULL,
    WARNING_THRESHOLD_FRACTION        NUMERIC NOT NULL,

    CONSTRAINT CO_THRESHOLD_FRACTION_RANGE
        CHECK ( 0 <= WARNING_THRESHOLD_FRACTION AND WARNING_THRESHOLD_FRACTION <= 1 ),

    PRIMARY KEY (OWNER_ID, CATEGORY_ID, ID),

    CONSTRAINT FK_CATEGORY_BUDGET_TO_OWNER
        FOREIGN KEY (OWNER_ID) REFERENCES USERS (ID),

    CONSTRAINT FK_CATEGORY_BUDGET_TO_CATEGORY
        FOREIGN KEY (OWNER_ID, CATEGORY_ID) REFERENCES CATEGORY (OWNER_ID, ID)
);
