CREATE INDEX IF NOT EXISTS IDX_TURNOVER_ROW_DATE
    ON TURNOVER_ROW (DATE);

CREATE INDEX IF NOT EXISTS IDX_TURNOVER_ROW_RECIPIENT
    ON TURNOVER_ROW (RECIPIENT);

CREATE INDEX IF NOT EXISTS IDX_TURNOVER_ROW_DESCRIPTION
    ON TURNOVER_ROW (DESCRIPTION);

CREATE INDEX IF NOT EXISTS IDX_TURNOVER_ROW_SIMILARITY_CHECKSUM
    ON TURNOVER_ROW (SIMILARITY_CHECKSUM);
