CREATE UNIQUE INDEX UQ_CATEGORY_ID ON CATEGORY (ID);

CREATE UNIQUE INDEX UQ_TURNOVER_FILE_ID ON TURNOVER_FILE_IMPORT (ID);

CREATE UNIQUE INDEX UQ_BANK_STATEMENT_ID ON BANK_STATEMENT (ID);

CREATE UNIQUE INDEX UQ_FINANCIAL_TRANSACTION_ID ON FINANCIAL_TRANSACTION (ID);

ALTER TABLE TURNOVER_ROW
    RENAME CONSTRAINT TURNOVER_ROW_ID_KEY TO UQ_TURNOVER_ROW_ID;
