ALTER TABLE TURNOVER_FILE_IMPORT
    ADD COLUMN TURNOVER_FILE_FORMAT TEXT;

UPDATE TURNOVER_FILE_IMPORT
SET TURNOVER_FILE_FORMAT = 'VR_BANK_CSV';

ALTER TABLE TURNOVER_FILE_IMPORT
    ALTER TURNOVER_FILE_FORMAT SET NOT NULL;

ALTER TABLE TURNOVER_FILE_IMPORT
    ADD CHECK ( TURNOVER_FILE_FORMAT IN ('VR_BANK_CSV') );
