version: "3.7"

services:
  database:
    container_name: "postgresql-database-release"
    image: "postgres:11"
    ports:
      - "40010:5432"
    networks:
      - release-regular-income
    volumes:
      - release-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "scott"
      POSTGRES_PASSWORD: "tiger"

  backend:
    container_name: "regular-income-backend"
    image: "${DOCKER_REGISTRY}/regular-income-backend:${REGULAR_INCOME_TAG}"
    ports:
      - "40001:8080"
    networks:
      - release-regular-income
    environment:
      config.jdbc.url: "jdbc:postgresql://postgresql-database-release:5432/scott"
      config.jdbc.user: "scott"
      config.jdbc.password: "tiger"
      config.jdbc.schema: "public"

  frontend:
    container_name: "regular-income-frontend"
    image: "${DOCKER_REGISTRY}/regular-income-frontend:${REGULAR_INCOME_TAG}"
    ports:
      - "40000:8080"
    networks:
      - release-regular-income
    environment:
      VUE_APP_CONFIG_BACKEND_URL: "http://regular-income-backend:8080"

networks:
  release-regular-income:

volumes:
  release-db-data:
