CREATE TABLE FINANCIAL_TRANSACTION
(
    ID                 UUID    NOT NULL UNIQUE,
    DATE_RECORD        DATE    NOT NULL,
    AMOUNT_VALUE_CENTS INTEGER NOT NULL,
    IS_PERIODIC        BOOLEAN,
    REASON             TEXT    NOT NULL,
    CHECKSUM           TEXT    NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE BANK_STATEMENT
(
    ID                   UUID    NOT NULL UNIQUE,
    DATE_RECORD          DATE    NOT NULL,
    AMOUNT_BALANCE_CENTS INTEGER NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE CATEGORY
(
    ID          UUID    NOT NULL UNIQUE,
    NAME        TEXT    NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    PATTERN     TEXT    NOT NULL UNIQUE,
    SORTING_KEY NUMERIC NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE TRANSACTION_CATEGORY_XREF
(
    TRANSACTION_ID UUID NOT NULL,
    CATEGORY_ID    UUID NOT NULL,

    PRIMARY KEY (TRANSACTION_ID, CATEGORY_ID),
    UNIQUE (TRANSACTION_ID, CATEGORY_ID),
    FOREIGN KEY (TRANSACTION_ID) REFERENCES FINANCIAL_TRANSACTION (ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID)
);
