CREATE TABLE TURNOVER_FILE_IMPORT
(
    ID                UUID                     NOT NULL UNIQUE,

    IMPORTED_AT       TIMESTAMP WITH TIME ZONE NOT NULL,

    FILENAME          TEXT                     NOT NULL,
    FILE_SIZE         BIGINT                   NOT NULL,
    FILE_CONTENT_TYPE TEXT                     NOT NULL,
    FILE_CONTENT      BYTEA                    NOT NULL,

    CHECKSUM          TEXT                     NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE TURNOVER_ROW
(
    ID                 TEXT    NOT NULL UNIQUE,
    TURNOVER_FILE      UUID    NOT NULL,

    DATE               DATE    NOT NULL,
    AMOUNT_VALUE_CENTS INTEGER NOT NULL,
    DESCRIPTION        TEXT    NOT NULL,
    SUGGESTED_CATEGORY TEXT    NOT NULL,
    RECIPIENT          TEXT    NOT NULL,

    CHECKSUM           TEXT    NOT NULL UNIQUe,
    CATEGORY_ID        UUID    NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (TURNOVER_FILE) REFERENCES TURNOVER_FILE_IMPORT (ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES category (ID),

    CHECK ( ID = CHECKSUM )
);

CREATE UNIQUE INDEX UQ_TURNOVER_ROW_CHECKSUM ON TURNOVER_ROW (CHECKSUM);
