DROP INDEX UQ_TURNOVER_ROW_CHECKSUM;

ALTER TABLE TURNOVER_ROW
    DROP CONSTRAINT TURNOVER_ROW_CHECK,
    DROP CONSTRAINT TURNOVER_ROW_CHECKSUM_KEY,
    DROP CONSTRAINT TURNOVER_ROW_PKEY;

ALTER TABLE TURNOVER_ROW
    DROP COLUMN ID;

ALTER TABLE TURNOVER_ROW
    ADD COLUMN ID UUID UNIQUE;

UPDATE TURNOVER_ROW
SET ID = uuid_generate_v4();

ALTER TABLE TURNOVER_ROW
    ALTER ID SET NOT NULL,
    ADD PRIMARY KEY (OWNER_ID, TURNOVER_FILE, ID);

CREATE UNIQUE INDEX UQ_TURNOVER_ROW_CHECKSUM ON TURNOVER_ROW (OWNER_ID, CHECKSUM);
