DROP VIEW V_ORDERED_BANK_STATEMENTS;

CREATE VIEW V_ORDERED_BANK_STATEMENTS
AS (
    WITH RECURSIVE CTE AS (
        SELECT *, 0 AS RANK
        FROM BANK_STATEMENT
        WHERE PREVIOUS_STATEMENT_ID IS NULL

        UNION ALL
        SELECT e.*, C.RANK + 1
        FROM CTE c
                 JOIN BANK_STATEMENT e ON e.PREVIOUS_STATEMENT_ID = c.ID
    )
    SELECT *
    FROM CTE
);
