ALTER TABLE TURNOVER_ROW
    ADD COLUMN SIMILARITY_CHECKSUM TEXT;

UPDATE TURNOVER_ROW
SET SIMILARITY_CHECKSUM = UPPER(MD5(AMOUNT_VALUE_CENTS || RECIPIENT || DESCRIPTION));

ALTER TABLE TURNOVER_ROW
    ALTER COLUMN SIMILARITY_CHECKSUM SET NOT NULL;

ALTER TABLE TURNOVER_ROW
    ADD CONSTRAINT CO_SIMILARITY_CHECKSUM_IS_UPPERCASE
        CHECK ( SIMILARITY_CHECKSUM = UPPER(SIMILARITY_CHECKSUM) );

ALTER TABLE TURNOVER_ROW
    ADD CONSTRAINT CO_SIMILARITY_CHECKSUM_IS_ON_SIMILAR_DATA
        CHECK ( SIMILARITY_CHECKSUM = UPPER(MD5(AMOUNT_VALUE_CENTS || RECIPIENT || DESCRIPTION)));
