UPDATE TURNOVER_ROW
SET CHECKSUM = UPPER(CHECKSUM);

ALTER TABLE TURNOVER_ROW
    ADD CONSTRAINT CO_CHECKSUM_IS_UPPERCASE
        CHECK ( CHECKSUM = UPPER(CHECKSUM) );

ALTER TABLE TURNOVER_ROW
    ADD CONSTRAINT CO_CHECKSUM_IS_ON_CHOSEN_DATA
        CHECK ( CHECKSUM = UPPER(MD5(DATE::TEXT || AMOUNT_VALUE_CENTS || DESCRIPTION || RECIPIENT)));
