ALTER TABLE TURNOVER_ROW
    DROP CONSTRAINT TURNOVER_ROW_CATEGORY_ID_FKEY;
ALTER TABLE FINANCIAL_TRANSACTION
    DROP CONSTRAINT FINANCIAL_TRANSACTION_CATEGORY_ID_FKEY;
ALTER TABLE CATEGORY
    DROP CONSTRAINT CATEGORY_PARENT_CATEGORY_FKEY;

ALTER TABLE CATEGORY
    DROP CONSTRAINT CATEGORY_PKEY;
ALTER TABLE CATEGORY
    ADD PRIMARY KEY (OWNER_ID, ID);

ALTER TABLE category
    ADD CONSTRAINT FK_CATEGORY_PARENT_CATEGORY
        FOREIGN KEY (parent_category, owner_id)
            REFERENCES category (ID, owner_id);
