ALTER TABLE BANK_STATEMENT
    ADD COLUMN OWNER_ID UUID;

UPDATE BANK_STATEMENT
SET OWNER_ID = (SELECT ID FROM USERS LIMIT 1);

ALTER TABLE BANK_STATEMENT
    ALTER OWNER_ID SET NOT NULL;

ALTER TABLE FINANCIAL_TRANSACTION
    DROP CONSTRAINT FINANCIAL_TRANSACTION_BANK_STATEMENT_ID_FKEY;

ALTER TABLE BANK_STATEMENT
    DROP CONSTRAINT BANK_STATEMENT_PREVIOUS_STATEMENT_ID_FKEY,
    DROP CONSTRAINT BANK_STATEMENT_PKEY,
    DROP CONSTRAINT BANK_STATEMENT_PREVIOUS_STATEMENT_ID_KEY;

ALTER TABLE BANK_STATEMENT
    ADD PRIMARY KEY (OWNER_ID, ID);

ALTER TABLE BANK_STATEMENT
    ADD CONSTRAINT FK_BAK_STATEMENT_PREVIOUS_STATEMENT
        FOREIGN KEY (PREVIOUS_STATEMENT_ID, OWNER_ID)
            REFERENCES BANK_STATEMENT (ID, OWNER_ID);
