ALTER TABLE FINANCIAL_TRANSACTION
    ADD COLUMN OWNER_ID UUID;

UPDATE FINANCIAL_TRANSACTION
SET OWNER_ID = (SELECT ID FROM USERS LIMIT 1);

ALTER TABLE FINANCIAL_TRANSACTION
    ALTER OWNER_ID SET NOT NULL;

ALTER TABLE FINANCIAL_TRANSACTION
    DROP CONSTRAINT FINANCIAL_TRANSACTION_PKEY;

DROP INDEX IDX_FK_TRANSACTION_X_STATEMENT;

ALTER TABLE FINANCIAL_TRANSACTION
    ADD PRIMARY KEY (OWNER_ID, BANK_STATEMENT_ID, ID);

ALTER TABLE FINANCIAL_TRANSACTION
    ADD CONSTRAINT FK_FINANCIAL_TRANSACTION_TO_BANK_STATEMENT
        FOREIGN KEY (OWNER_ID, BANK_STATEMENT_ID)
            REFERENCES BANK_STATEMENT (OWNER_ID, ID);
