CREATE TABLE BACKUP_HISTORY
(
    ID             UUID                     NOT NULL UNIQUE,
    LAST_CHECK     TIMESTAMP WITH TIME ZONE NOT NULL,
    HAD_WORK_TO_DO BOOLEAN                  NOT NULL,

    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_BACKUP_LAST_CHECK ON BACKUP_HISTORY (LAST_CHECK);
