ALTER TABLE TURNOVER_FILE_IMPORT
    ADD COLUMN OWNER_ID UUID;

UPDATE TURNOVER_FILE_IMPORT
SET OWNER_ID = (SELECT ID FROM USERS LIMIT 1);

ALTER TABLE TURNOVER_FILE_IMPORT
    ALTER OWNER_ID SET NOT NULL;

ALTER TABLE TURNOVER_FILE_IMPORT
    ADD CONSTRAINT FK_TURNOVER_FILE_IMPORT_OWNER
        FOREIGN KEY (OWNER_ID)
            REFERENCES USERS (ID);

CREATE INDEX IDX_TURNOVER_FILE_IMPORT_OWNER
    ON TURNOVER_FILE_IMPORT (OWNER_ID);

-- Add owner as primary key
ALTER TABLE TURNOVER_ROW
    DROP CONSTRAINT TURNOVER_ROW_TURNOVER_FILE_FKEY;
ALTER TABLE TURNOVER_FILE_IMPORT
    DROP CONSTRAINT TURNOVER_FILE_IMPORT_PKEY;
ALTER TABLE TURNOVER_FILE_IMPORT
    ADD PRIMARY KEY (OWNER_ID, ID);
