name: Build Branch

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:  # Allow manual triggering from the GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          fetch-tags: 'true'

      - name: Get release version
        id: get_release_version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: 'false'
          bump_each_commit_patch_pattern: ''
          tag_prefix: 'v'
          major_pattern: 'feat:'
          minor_pattern: 'fix:'
          search_commit_body: 'true'

      - name: Info release version
        run: |
          latest_release=$(gh release view --json name --jq '.name')
          echo "Latest release: $latest_release"
          echo "New Version: $RELEASE_VERSION"
          echo "New Version Tag: $RELEASE_VERSION_TAG"
        env:
          RELEASE_VERSION: ${{ steps.get_release_version.outputs.version }}
          RELEASE_VERSION_TAG: ${{ steps.get_release_version.outputs.version_tag }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build --info --stacktrace

      - name: Jib
        run: ./gradlew jibDockerBuild --info --stacktrace
